version: '2'

services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - local-data:/data
volumes:
  local-data:
    driver: local
    driver_opts:
      type: nfs
      device: /dockers/portainer/data
      o: bind
